name: 'Trigger DBT Cloud Job'
description: 'Triggers a DBT cloud job specified by the job id.'
branding:
  icon: 'cloud-lightning'
  color: 'orange'
inputs:
  dbt_cloud_token:  # token for dbt cloud api
    description: 'DBT cloud api token'
    required: true
  dbt_cloud_account_id:  # account id
    description: 'DBT cloud account id'
    required: true
  dbt_cloud_job_id:  # job id
    description: 'DBT cloud job id'
    required: true
  dbt_cloud_timeout:  # dbt API timeout in ms
    description: 'Timeout in ms used in DBT Cloud API calls'
    required: true
    default: '1000'
  cause:  # cause
    description: 'Cause message to use'
    required: true
    default: 'Triggered from Github'
  interval:  # interval
    description: 'The interval between polls in seconds.'
    required: false
    default: '30'
  git_sha:
    description: 'The git sha to check out before running this job'
    required: false
  git_branch:
    description: 'The git branch to check out before running this job'
    required: false
  schema_override:
    description: 'Override the destination schema in the configured target for this job'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
